/** English follows the guide's Chinese script; the audio remains Chinese. */
export const englishSubtitles: Readonly<Record<string, string>> = {
  'c0-0': 'Come closer to this mural. Meet Zhang Qian and his delegation, then follow their footsteps on this long journey.',
  'c0-1': 'The palace is at the upper right, the farewell below, and the city at the upper left. These three scenes tell a story of travelling west.',
  'c0-2': 'Let us begin with the two golden figures in the palace. Why does the emperor worship them, and why does he send Zhang Qian west?',
  'c1-0': 'Look at Ganquan Palace in the upper right. Two golden figures stand inside, while Emperor Wu of Han and his officials bow before them.',
  'c1-1': 'In this mural, the golden figures are shown as Buddhas. The emperor does not yet know their names, so he wants someone to ask far away.',
  'c1-2': 'This question in the palace sets Zhang Qian on his journey west. Remember: this is the reason for the mission told by the mural.',
  'c2-0': 'Look below. The emperor is on horseback; Zhang Qian kneels opposite him, holding a ceremonial tablet. He is about to receive his orders.',
  'c2-1': 'Zhang Qian originally sought the Yuezhi as allies against the Xiongnu. Yet this mural turns the journey into a search for the identity of Buddhist images.',
  'c2-2': 'The Xiongnu had defeated the Yuezhi and killed their king. Zhang Qian set out to seek an alliance, but the mural begins with the golden figures.',
  'c3-0': 'Now return to the left of the mural. A delegation emerges among the rocks. The winding mountain road links the farewell to the arrival.',
  'c3-1': 'Zhang Qian’s journey was difficult. The Xiongnu intercepted him and held him for over ten years. This camp scene illustrates that interruption.',
  'c3-2': 'After escaping, he did not turn for home. He continued west through Dayuan and Kangju in search of the Great Yuezhi.',
  'c4-0': 'Look at the staff carried by the attendant. It represents the authority of a Han envoy and the mission Zhang Qian never abandoned.',
  'c4-1': 'After more than ten years in captivity, the Han envoy’s staff remained. Zhang Qian still remembered the task entrusted to him.',
  'c4-2': 'But the Yuezhi had settled peacefully in the west and did not wish to fight over an old grievance. Zhang Qian arrived, yet the alliance did not happen.',
  'c5-0': 'Look again at the upper left. The envoy approaches the gate of Daxia. Monks wait outside and a Buddhist tower stands within: the mural’s destination.',
  'c5-1': 'Step into this scene of Daxia to see its buildings and market. Merchants and traded goods bring this distant world into view.',
  'c5-2': 'On the table are cloth and bamboo staffs from Sichuan. Traded through Shendu, they had reached distant Daxia.',
  'c6-0': 'Return to the gate. Look at the two monks, then the Buddhist tower inside. They answer the question about the golden figures in Ganquan Palace.',
  'c6-1': 'The mystery is resolved: in the mural’s story, the golden figures are Buddhas, and the journey becomes a search for knowledge of Buddhism.',
  'c6-2': 'Early Tang painters used Zhang Qian’s fame to give Buddhism an earlier history. The monks and tower preserve a later memory of the past.',
  'c7-0': 'Finally, step back to see the whole mural. Can you now connect the palace, the farewell, the mountain road and the city gate?',
  'c7-1': 'Zhang Qian returned to Han territory after thirteen years with knowledge of the Western Regions. The alliance failed, but his journey opened the way for later contact.',
  'c7-2': 'Take one last look. This mural remembers an envoy’s journey and shows us how later generations retold his story.',
}
