/** English translates the story; recordings remain Chinese. */
export const englishSubtitles: Readonly<Record<string, string>> = {
  "c0-0": "Emperor Wu of Han wanted an ally against the Xiongnu. Zhang Qian’s story began with that mission.",
  "c0-1": "The intended ally was the Yuezhi. Defeated by the Xiongnu, their king killed, they had moved west. The emperor hoped they would join forces against their shared enemy.",
  "c0-2": "Reaching the Yuezhi meant crossing territory controlled by the Xiongnu. No one knew what lay ahead. Zhang Qian volunteered for the mission.",
  "c1-0": "Zhang Qian set out west from Longxi with over a hundred people. Ganfu, a Hu companion skilled with a bow, would play an important part in their journey.",
  "c1-1": "Before they could reach the Yuezhi, the Xiongnu intercepted them. Refused passage, Zhang Qian was brought before the chanyu, the Xiongnu ruler. The mission came to a halt.",
  "c1-2": "Held among the Xiongnu for over ten years, Zhang Qian married and had a child. Yet he kept his Han envoy’s credential and did not abandon the mission.",
  "c2-0": "After more than ten years, surveillance relaxed and Zhang Qian escaped with companions. Instead of heading home, he continued west to find the Yuezhi.",
  "c2-1": "When food was scarce, Ganfu used his skill with a bow to hunt for them. Travelling west also meant finding a way through the borders of unfamiliar countries.",
  "c2-2": "Hoping for contact with Han, the people of Dayuan escorted them to Kangju. Kangju sent them onward, and Zhang Qian finally reached the Great Yuezhi.",
  "c3-0": "But the Yuezhi had settled in fertile land with fewer disturbances. They did not want to renew a war against the Xiongnu over an old grievance.",
  "c3-1": "Han hoped to attack the Xiongnu from two sides. The Yuezhi saw Han as distant and war as a threat to their present peace. Their interests had diverged.",
  "c3-2": "Zhang Qian went from the Yuezhi to Daxia and stayed for over a year, but could not secure an alliance. He prepared to return with news of what he had seen.",
  "c4-0": "The alliance failed, but the journey revealed another world. Daxia had towns and markets, where merchants traded goods from different lands.",
  "c4-1": "In the market he recognized cloth and bamboo staffs from Sichuan. How had such familiar goods reached somewhere so far away?",
  "c4-2": "People in Daxia said merchants bought them in Shendu, the Indian region. Zhang Qian inferred that Sichuan might have another route west.",
  "c5-0": "On his return, Zhang Qian hoped to pass along the southern mountains and through Qiang territory to avoid the Xiongnu. He was captured again and held for over a year.",
  "c5-1": "Disorder among the Xiongnu gave him another chance to escape. He returned to Han with his wife and Ganfu. His first mission had taken thirteen years.",
  "c5-2": "Of the original party of over a hundred, only Zhang Qian and Ganfu returned. There was no alliance, but his knowledge of the Western Regions gave the court new possibilities.",
  "c6-0": "Emperor Wu learned about Dayuan, Kangju, the Great Yuezhi and Daxia. Beyond the Xiongnu were many countries with which Han could seek direct contact.",
  "c6-1": "On a later mission, Zhang Qian contacted the Wusun and sent deputy envoys to other countries. The Wusun did not immediately commit to joint action, but exchanges of envoys grew.",
  "c6-2": "Trade routes already existed. Zhang Qian did not create the entire Silk Road alone; his journeys helped Han establish more direct contact with countries to the west.",
  "c7-0": "In the early Tang, painters at Dunhuang put Zhang Qian into this mural. The farewell below, mountain journey and welcome at the gate show how later generations remembered him.",
  "c7-1": "But the mural gives a different reason: the emperor worships golden figures and sends Zhang Qian west to learn their names. Monks and a Buddhist tower supply the answer in a later Buddhist retelling.",
  "c7-2": "Zhang Qian left to seek an ally. Later generations used his journey to tell a story about Buddhism. Knowing his experience helps us distinguish the history from its later memory."
}
